# Generated by Django 4.2.30 on 2026-10-04 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nombre de la Sala')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Código de la Sala')),
                ('capacity', models.PositiveIntegerField(verbose_name='Capacidad Máxima de Asistentes')),
                ('description', models.TextField(blank=True, verbose_name='Descripción / Equipamiento')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activa / Disponible para Reservas')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Sala',
                'verbose_name_plural': 'Salas',
                'ordering': ['code'],
            },
        ),
    ]
