# Generated by Django 4.2.30 on 2026-10-04 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Fecha de Reserva')),
                ('start_time', models.TimeField(verbose_name='Hora Inicio')),
                ('end_time', models.TimeField(verbose_name='Hora Término')),
                ('attendees_count', models.PositiveIntegerField(verbose_name='Cantidad de Asistentes')),
                ('status', models.CharField(choices=[('CONFIRMADA', 'Confirmada'), ('CANCELADA', 'Cancelada'), ('NO_SHOW', 'No-Show')], default='CONFIRMADA', max_length=20, verbose_name='Estado de la Reserva')),
                ('noshow_registered_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha/Hora Registro No-Show')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Reserva',
                'verbose_name_plural': 'Reservas',
                'ordering': ['-date', '-start_time'],
            },
        ),
    ]
